import { CommonModule } from '@angular/common';
import { Component, inject, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { Member, Project, ProjectOverview, Sprint } from '../../../core/models/app-models';
import { ProjectMemberService } from '../../../core/services/project-member.service';
import { ProjectService } from '../../../core/services/project.service';
import { SprintService } from '../../../core/services/sprint.service';

@Component({ selector:'app-project-detail', standalone:true, imports:[CommonModule, FormsModule, RouterLink], template:`
  @if (project()) { <section class="page-card"><header><div><p class="eyebrow">PROJECT WORKSPACE</p><h2>{{ project()!.name }} <small>{{ project()!.key }}</small></h2><p>{{ project()!.description }}</p></div><div class="actions"><a [routerLink]="['/projects', projectId, 'backlog']">Backlog</a><a [routerLink]="['/projects', projectId, 'board']">Open board</a></div></header>
  <nav><a [routerLink]="['/projects',projectId]">Overview</a><a [routerLink]="['/projects',projectId,'backlog']">Backlog</a><a [routerLink]="['/projects',projectId,'board']">Board</a><button (click)="tab.set('members')">Members</button><button (click)="tab.set('sprints')">Sprints</button><button (click)="tab.set('settings')">Settings</button></nav>
  @if (tab()==='overview' && overview()) { <div class="metrics"><article><b>{{ overview()!.total_tasks }}</b>Total tasks</article><article><b>{{ overview()!.active_tasks }}</b>Active</article><article><b>{{ overview()!.completed_tasks }}</b>Done</article><article><b>{{ overview()!.member_count }}</b>Members</article></div><div class="progress"><span [style.width.%]="progress()"></span></div><p>{{ overview()!.summary }}</p> }
  @if (tab()==='members') { <form class="inline" (ngSubmit)="invite()"><input [(ngModel)]="inviteUserId" name="userId" placeholder="User UUID" required><select [(ngModel)]="inviteRole" name="role"><option value="member">Member</option><option value="admin">Admin</option><option value="viewer">Viewer</option></select><button>Invite</button></form><input [(ngModel)]="memberSearch" placeholder="Search members"><table><tr><th>Member</th><th>Email</th><th>Role</th><th></th></tr>@for (member of filteredMembers(); track member.id) {<tr><td>{{member.user_name || member.user_id}}</td><td>{{member.user_email}}</td><td><select [ngModel]="member.role" (ngModelChange)="changeRole(member,$event)"><option value="admin">Admin</option><option value="member">Member</option><option value="viewer">Viewer</option></select></td><td><button (click)="remove(member)">Remove</button></td></tr>}</table> }
  @if (tab()==='sprints') { <form class="form" (ngSubmit)="saveSprint()"><input [(ngModel)]="sprintDraft.name" name="sprintName" placeholder="Sprint name" required><input [(ngModel)]="sprintDraft.goal" name="goal" placeholder="Goal"><input [(ngModel)]="sprintDraft.start_date" name="start" type="date"><input [(ngModel)]="sprintDraft.end_date" name="end" type="date"><button>Create sprint</button></form>@for (sprint of sprints();track sprint.id){<article class="row"><b>{{sprint.name}}</b><span>{{sprint.goal}}</span><button (click)="toggleSprint(sprint)">{{sprint.is_active ? 'Close' : 'Activate'}}</button></article>} }
  @if (tab()==='settings') { <form class="form" (ngSubmit)="saveProject()"><input [(ngModel)]="project()!.name" name="name" required><textarea [(ngModel)]="project()!.description" name="description"></textarea><label><input [(ngModel)]="project()!.is_active" name="active" type="checkbox"> Active</label><button>Save settings</button></form><button class="danger" (click)="deleteProject()">Delete project</button> }
  </section> }`, styles:[`.page-card{padding:20px}.eyebrow{color:#6366f1;font-size:.7rem;font-weight:800;letter-spacing:.12em;margin:0}header,nav,.inline,.row,.actions{display:flex;gap:12px;align-items:center;justify-content:space-between;flex-wrap:wrap}.actions a,nav a{padding:9px 11px;border:1px solid #dbe5f1;border-radius:8px;text-decoration:none;color:#334155}nav{justify-content:start;margin-top:18px;border-bottom:1px solid #e2e8f0;padding-bottom:12px}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:18px 0}.metrics article,.form,.row{border:1px solid #334155;padding:14px;border-radius:10px}.metrics b{display:block;font-size:1.8rem}.progress{height:10px;background:#334155;border-radius:8px}.progress span{display:block;background:#7c3aed;height:100%;border-radius:8px}.form{display:grid;gap:10px;margin-top:16px;max-width:520px}input,textarea,select{padding:8px}table{width:100%;margin-top:12px;text-align:left}.danger{background:#b91c1c}`] })
export class ProjectDetailPage implements OnInit { private readonly route=inject(ActivatedRoute); private readonly router=inject(Router); private readonly projects=inject(ProjectService); private readonly membersApi=inject(ProjectMemberService); private readonly sprintsApi=inject(SprintService); protected projectId=''; protected readonly project=signal<Project|null>(null); protected readonly overview=signal<ProjectOverview|null>(null); protected readonly members=signal<Member[]>([]); protected readonly sprints=signal<Sprint[]>([]); protected readonly tab=signal('overview'); protected inviteUserId=''; protected inviteRole:Member['role']='member'; protected memberSearch=''; protected sprintDraft:Partial<Sprint>={name:'',goal:''}; ngOnInit(){this.projectId=this.route.snapshot.paramMap.get('id')||'';this.load();} protected progress(){const o=this.overview();return o?.total_tasks?Math.round(o.completed_tasks/o.total_tasks*100):0;} protected filteredMembers(){const q=this.memberSearch.toLowerCase();return this.members().filter(m=>`${m.user_name} ${m.user_email} ${m.user_id}`.toLowerCase().includes(q));} protected invite(){if(this.inviteUserId)this.membersApi.invite(this.projectId,this.inviteUserId,this.inviteRole).subscribe(()=>this.loadMembers());} protected changeRole(m:Member,role:Member['role']){this.membersApi.updateRole(this.projectId,m.user_id,role).subscribe(()=>this.loadMembers());} protected remove(m:Member){if(confirm('Remove this member?'))this.membersApi.remove(this.projectId,m.user_id).subscribe(()=>this.loadMembers());} protected saveSprint(){this.sprintsApi.create(this.projectId,this.sprintDraft).subscribe(()=>{this.sprintDraft={name:'',goal:''};this.loadSprints();});} protected toggleSprint(s:Sprint){this.sprintsApi.update(this.projectId,s.id,{is_active:!s.is_active}).subscribe(()=>this.loadSprints());} protected saveProject(){const p=this.project();if(p)this.projects.updateProject(p.id,{name:p.name,description:p.description,is_active:p.is_active}).subscribe(v=>this.project.set(v));} protected deleteProject(){const p=this.project();if(p&&confirm(`Delete ${p.name}?`))this.projects.deleteProject(p.id).subscribe(()=>this.router.navigateByUrl('/projects'));} private load(){this.projects.getProject(this.projectId).subscribe(p=>this.project.set(p));this.membersApi.overview(this.projectId).subscribe(o=>this.overview.set(o));this.loadMembers();this.loadSprints();} private loadMembers(){this.membersApi.members(this.projectId).subscribe(v=>this.members.set(v));} private loadSprints(){this.sprintsApi.list(this.projectId).subscribe(v=>this.sprints.set(v));} }
